FROM mcr.microsoft.com/dotnet/aspnet:10.0 AS base
WORKDIR /app
EXPOSE 8080
EXPOSE 8081

FROM mcr.microsoft.com/dotnet/sdk:10.0 AS build
ARG BUILD_CONFIGURATION=Release
WORKDIR /src
COPY ["src/API/AssetManagement.Api/AssetManagement.Api.csproj", "src/API/AssetManagement.Api/"]
# Copy các project tham chiếu khác ở đây nếu có
RUN dotnet restore "./src/API/AssetManagement.Api/AssetManagement.Api.csproj"
COPY . .
WORKDIR "/src/src/API/AssetManagement.Api"
RUN dotnet build "./AssetManagement.Api.csproj" -c $BUILD_CONFIGURATION -o /app/build

FROM build AS publish
ARG BUILD_CONFIGURATION=Release
RUN dotnet publish "./AssetManagement.Api.csproj" -c $BUILD_CONFIGURATION -o /app/publish /p:UseAppHost=false

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "AssetManagement.Api.dll"]
