FROM mcr.microsoft.com/dotnet/aspnet:10.0 AS base
USER app
WORKDIR /app
EXPOSE 8080
EXPOSE 8081

FROM mcr.microsoft.com/dotnet/sdk:10.0 AS build
ARG BUILD_CONFIGURATION=Release
WORKDIR /src
COPY ["Directory.Build.props", "."]
COPY ["src/API/Assetly.Api/Assetly.Api.csproj", "src/API/Assetly.Api/"]
COPY ["src/Modules/Assets/Assetly.Modules.Assets.Infrastructure/Assetly.Modules.Assets.Infrastructure.csproj", "src/Modules/Assets/Assetly.Modules.Assets.Infrastructure/"]
COPY ["src/Modules/Assets/Assetly.Modules.Assets.Application/Assetly.Modules.Assets.Application.csproj", "src/Modules/Assets/Assetly.Modules.Assets.Application/"]
COPY ["src/Modules/Assets/Assetly.Modules.Assets.Domain/Assetly.Modules.Assets.Domain.csproj", "src/Modules/Assets/Assetly.Modules.Assets.Domain/"]
COPY ["src/Modules/Assets/Assetly.Modules.Assets.Presentation/Assetly.Modules.Assets.Presentation.csproj", "src/Modules/Assets/Assetly.Modules.Assets.Presentation/"]
RUN dotnet restore "./src/API/Assetly.Api/Assetly.Api.csproj"
COPY . .
WORKDIR "/src/src/API/Assetly.Api"
RUN dotnet build "./Assetly.Api.csproj" -c $BUILD_CONFIGURATION -o /app/build

FROM build AS publish
ARG BUILD_CONFIGURATION=Release
RUN dotnet publish "./Assetly.Api.csproj" -c $BUILD_CONFIGURATION -o /app/publish /p:UseAppHost=false

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "Assetly.Api.dll"]
