<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\Assetly.Modules.Assets.Domain\Assetly.Modules.Assets.Domain.csproj" />
    <ProjectReference Include="..\..\..\Shared\Assetly.Shared.Application\Assetly.Shared.Application.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
